// Generated by CoffeeScript 1.4.0
(function() {
  var app;

  app = angular.module('petitpoucet', ["ui.bootstrap", "ui.grid", 'ui.grid.edit', 'ngResource', 'ui.ace', 'ui.layout']);

  app.controller("TraceCtrl", function($scope, $resource, $timeout, $location, $anchorScroll) {
    var FilterFiles, GetRecordStatus, Refresh, SetRecordStatus, Source;
    Refresh = $resource('/trace/refresh');
    Source = $resource('/trace/getFile', {}, {
      "do": {
        method: 'POST'
      }
    });
    GetRecordStatus = $resource('/trace/getStatus');
    SetRecordStatus = $resource('/trace/setStatus/:status');
    FilterFiles = $resource('/trace/filterFiles', {}, {
      "do": {
        method: 'POST'
      }
    });
    $scope.refresh = function() {
      return Refresh.get({}, function(list) {
        $scope.funcs = list.result;
        return $scope.files = list.files;
      });
    };
    $scope.displaySrc = function(idx, spath, sline) {
      $scope.curIdx = idx;
      $scope.endIdx = $scope.funcs[idx].endidx;
      $scope.curFile = spath;
      return Source["do"]({
        fPath: spath
      }, function(result) {
        $scope.myFile = result.src;
        return $timeout(function() {
          $scope.editor.setReadOnly(true);
          $scope.editor.getSession().setMode("ace/mode/c_cpp");
          return $scope.editor.gotoLine(sline);
        });
      });
    };
    $scope.aceLoaded = function(editor) {
      return $scope.editor = editor;
    };
    $scope.record = function() {
      $scope.myFile = '';
      $scope.curFile = '';
      $scope.funcs = [];
      $scope.files = [];
      return SetRecordStatus.get({
        status: 1
      }, function(v) {
        return $scope.status = v.res;
      });
    };
    $scope.stop = function() {
      return SetRecordStatus.get({
        status: 0
      }, function(v) {
        $scope.status = v.res;
        return $scope.refresh();
      });
    };
    $scope.scrollTo = function(idx) {
      var key;
      key = "idx" + $scope.funcs[idx].endnum;
      $timeout(function() {
        $location.hash(key);
        return $anchorScroll();
      });
      idx = $scope.funcs[idx].endidx;
      return $scope.displaySrc(idx, $scope.funcs[idx].from_src, $scope.funcs[idx].from_line);
    };
    $scope.chk = function(idx) {
      if ((idx > $scope.curIdx) && (idx < $scope.endIdx)) {
        return true;
      }
      return false;
    };
    $scope.filesToFilter = function() {
      return FilterFiles["do"]({
        filefilter: $scope.files
      }, function(list) {
        $scope.funcs = list.result;
        return $scope.files = list.files;
      });
    };
    $scope.curFile = '';
    $scope.curIdx = 0;
    GetRecordStatus.get({}, function(v) {
      return $scope.status = v.res;
    });
    return $scope.refresh();
  });

}).call(this);
